# Generated by Django 4.0.7 on 2023-03-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_menuitem_discount_menuitem_rating_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=15),
        ),
    ]
