# Generated by Django 4.0.7 on 2023-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Japanese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Japanese_images/')),
                ('price', models.DecimalField(decimal_places=2, default=500.0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=5.0, max_digits=15)),
                ('rating', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
            ],
        ),
    ]
