# Generated by Django 4.0.7 on 2023-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='Cat_images/'),
        ),
    ]
