# Generated by Django 4.0.7 on 2023-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_fooditem_remove_book_author_delete_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(null=True, upload_to='menu_images/'),
        ),
    ]
