# Generated by Django 4.0.7 on 2023-03-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('china', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.china')),
                ('japan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.japan')),
                ('nigeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Search.nigeria')),
            ],
        ),
    ]
